### ISSUE TITLE
Website not reachable

### ISSUE THREAD

**Issue by ffflorian** [LingDong-/shan-shui-inf#3]
![screenshot from 2018-11-21 15-58-27](https://user-images.githubusercontent.com/5497598/48849305-574fc600-eda6-11e8-9c21-a635213c62e7.png)

The URL https://lingdong-.github.io/shan-shui-inf/ is not reachable [for many people](https://www.whatsmydns.net/#A/lingdong-.github.io) since hyphens are [not allowed](https://stackoverflow.com/a/7111947) as ending character of subdomain names.

**Comment by LingDong-** [comment]
Thanks a lot for pointing that out! Unfortunately GitHub pages subdomain name seems to be bound to my username. So I added an alternative link in README.md as a temporary fix. (https://shan-shui-inf.glitch.me)

**Comment by ffflorian** [comment]
The alternative link works :slightly_smiling_face: Beautiful project, by the way.
